### ISSUE TITLE
Clarification Request

### ISSUE THREAD

**Issue by tboyko** [brightcove-archive/ooyala_retries#3]
What happens after the number of retries has been exhausted? Is the original exception raised, or does code execution continue after the enclosed block?

**Comment by cespare** [comment]
[The original exception is re-raised.](https://github.com/ooyala/retries/blob/027566c97fddc1e9509f8b36eaee8950c53ca122/lib/retries.rb#L48)

The other behavior would be terrible :)

**Comment by tboyko** [comment]
Thanks!
